services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: flick-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=flick
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=flick
    volumes:
      - flick-db-data:/var/lib/postgresql/data
    networks:
      - flick-network

networks:
  flick-network:
    name: flick-network

volumes:
  flick-db-data:
