services:
  db:
    image: postgres:17-alpine
    container_name: flick-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=flick
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=flick
    volumes:
      - flick-db-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - flick-network

networks:
  flick-network:
    name: flick-network
    driver: bridge

volumes:
  flick-db-data:
